apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    host: pod-info.scottsmith.me.uk 
    ingress:
      hosts:
        - host: pod-info.scottsmith.me.uk
          paths:
            - path: /
              pathType: ImplementationSpecific
