apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis
resources:
  - namespace.yml
  - release.yml
configMapGenerator:
  - name: redis-values
    files:
      - values.yaml=values.yml
configurations:
  - kustomizeconfig.yml
