---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  selector:
    matchLabels:
      app: website
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: wordpress
          envFrom:
          - secretRef:
            name: website-mysql
          - configMapRef:
            name: website-env
          ports:
            - containerPort: 80
