---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ingress-default-backend
  name: haproxy-kubernetes-ingress-default-backend
spec:
  selector:
    run: ingress-default-backend
  ports:
  - name: port-1
    port: 8080
    protocol: TCP
    targetPort: 8080
