apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-website
  labels:
    app: test-website
spec:
  selector:
    matchLabels:
      app: test-website
  replicas: 2
  template:
    metadata:
      labels:
        app: test-website
    spec:
      containers:
        - name: test-website
          image: scottsmith/test-image:5 # {"$imagepolicy": "flux-system:test"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
