---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test
resources:
  - flux-system-automation.yaml
  - test-image-policy.yaml
  - test-image-registry.yaml  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
