---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- test-image-policy.yaml
- test-image-registry.yaml
patchesJson6902:
  - target:
      kind: ImageRepository
      name: .*
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: flux-system
  - target:
      kind: ImagePolicy
      name: .*
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: flux-system