---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesJson6902:
- target:
    kind: .*
    name: .*
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: test
- target:
    kind: ImageRepository
    name: .*
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: flux-system
- target:
    kind: ImagePolicy
    name: .*
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: flux-system