---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: test-image
  namespace: test
spec:
  filterTags:
    extract: ts
    pattern: ^(?P<ts>[0-9]+)
  imageRepositoryRef:
    name: test-image
  policy:
    numerical:
      order: asc

