---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: app-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: ssh://git@github.com/scottasmith/git-ops-app-secrets
  secretRef:
    name: flux-system